import { Appliance } from "../types/appliance";

export const applianceHighUsageThreshold = 45; // kWh per month

export const appliancesMock: Appliance[] = [
  {
    id: "appliance-1",
    name: "Refrigerador inteligente",
    category: "kitchen",
    typicalWattage: 150,
    monthlyKWh: 55,
    usageHoursPerDay: 24,
    lastUpdated: "2025-11-10T08:15:00Z",
    description:
      "Refrigerador con doble puerta y modo ahorro nocturno. Mantiene temperaturas estables con sensores de humedad y compresor inverter.",
    monthlyHistory: [
      { label: "Jun", kWh: 61 },
      { label: "Jul", kWh: 59 },
      { label: "Ago", kWh: 57 },
      { label: "Sep", kWh: 58 },
      { label: "Oct", kWh: 56 },
      { label: "Nov", kWh: 55 },
    ],
    weeklyUsage: [
      { label: "Lun", kWh: 1.8 },
      { label: "Mar", kWh: 1.9 },
      { label: "Mié", kWh: 1.8 },
      { label: "Jue", kWh: 1.7 },
      { label: "Vie", kWh: 1.8 },
      { label: "Sáb", kWh: 1.9 },
      { label: "Dom", kWh: 2.0 },
    ],
  },
  {
    id: "appliance-2",
    name: "Horno eléctrico",
    category: "kitchen",
    typicalWattage: 2400,
    monthlyKWh: 38,
    usageHoursPerDay: 1.5,
    lastUpdated: "2025-11-12T14:45:00Z",
    description:
      "Horno con precalentamiento rápido y aislamiento térmico reforzado. Incluye modo de autolimpieza y control remoto.",
    monthlyHistory: [
      { label: "Jun", kWh: 42 },
      { label: "Jul", kWh: 39 },
      { label: "Ago", kWh: 37 },
      { label: "Sep", kWh: 36 },
      { label: "Oct", kWh: 38 },
      { label: "Nov", kWh: 38 },
    ],
    weeklyUsage: [
      { label: "Lun", kWh: 1.1 },
      { label: "Mar", kWh: 0.9 },
      { label: "Mié", kWh: 0.8 },
      { label: "Jue", kWh: 0.9 },
      { label: "Vie", kWh: 1.2 },
      { label: "Sáb", kWh: 1.5 },
      { label: "Dom", kWh: 1.3 },
    ],
  },
  {
    id: "appliance-3",
    name: "Aire acondicionado",
    category: "climate",
    typicalWattage: 1200,
    monthlyKWh: 72,
    usageHoursPerDay: 6,
    lastUpdated: "2025-11-15T19:20:00Z",
    description:
      "Unidad inverter con filtros HEPA y control por voz. Ajuste automático según ocupación y climatología.",
    monthlyHistory: [
      { label: "Jun", kWh: 88 },
      { label: "Jul", kWh: 85 },
      { label: "Ago", kWh: 80 },
      { label: "Sep", kWh: 76 },
      { label: "Oct", kWh: 74 },
      { label: "Nov", kWh: 72 },
    ],
    weeklyUsage: [
      { label: "Lun", kWh: 2.8 },
      { label: "Mar", kWh: 3.1 },
      { label: "Mié", kWh: 2.9 },
      { label: "Jue", kWh: 3.2 },
      { label: "Vie", kWh: 3.0 },
      { label: "Sáb", kWh: 3.4 },
      { label: "Dom", kWh: 3.3 },
    ],
  },
  {
    id: "appliance-4",
    name: "Lavadora inteligente",
    category: "laundry",
    typicalWattage: 500,
    monthlyKWh: 28,
    usageHoursPerDay: 0.8,
    lastUpdated: "2025-11-14T10:05:00Z",
    description:
      "Lavadora con dosificación automática de detergente y ciclos eco. Conectada a la red para programaciones remotas.",
    monthlyHistory: [
      { label: "Jun", kWh: 32 },
      { label: "Jul", kWh: 31 },
      { label: "Ago", kWh: 29 },
      { label: "Sep", kWh: 27 },
      { label: "Oct", kWh: 28 },
      { label: "Nov", kWh: 28 },
    ],
    weeklyUsage: [
      { label: "Lun", kWh: 0.9 },
      { label: "Mar", kWh: 0.8 },
      { label: "Mié", kWh: 0.9 },
      { label: "Jue", kWh: 0.7 },
      { label: "Vie", kWh: 0.8 },
      { label: "Sáb", kWh: 1.1 },
      { label: "Dom", kWh: 1.0 },
    ],
  },
  {
    id: "appliance-5",
    name: "Centro de entretenimiento",
    category: "entertainment",
    typicalWattage: 350,
    monthlyKWh: 33,
    usageHoursPerDay: 4,
    lastUpdated: "2025-11-13T21:42:00Z",
    description:
      "Televisor OLED con barra de sonido y consola integrada. Optimiza brillo y refresco según el contenido.",
    monthlyHistory: [
      { label: "Jun", kWh: 35 },
      { label: "Jul", kWh: 34 },
      { label: "Ago", kWh: 33 },
      { label: "Sep", kWh: 32 },
      { label: "Oct", kWh: 33 },
      { label: "Nov", kWh: 33 },
    ],
    weeklyUsage: [
      { label: "Lun", kWh: 1.0 },
      { label: "Mar", kWh: 0.9 },
      { label: "Mié", kWh: 1.1 },
      { label: "Jue", kWh: 0.8 },
      { label: "Vie", kWh: 1.0 },
      { label: "Sáb", kWh: 1.2 },
      { label: "Dom", kWh: 1.3 },
    ],
  },
];
